# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [4]:
5*np.ones(10)

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [5]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [6]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [7]:
np.arange(9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [9]:
np.random.rand()

0.31223032880999446

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [10]:
np.random.randn(25)

array([-0.88641158,  0.21919484, -0.28561795,  0.7103073 , -0.84190645,
        0.27965259, -0.48439128,  0.38106642,  0.1687573 ,  0.86177173,
        0.32351758, -1.08099664, -0.19939201, -0.73805874,  0.4352925 ,
       -1.45170128,  0.88169343, -1.20578457, -0.01046666, -0.22968549,
        0.25222047,  0.26851367,  0.301651  , -0.6056467 , -0.8910755 ])

#### Create the following matrix:

In [11]:
np.random.random_sample((10,10))

array([[0.09808582, 0.12855092, 0.77808591, 0.77995869, 0.62182686,
        0.4617628 , 0.58960859, 0.97456241, 0.69462929, 0.34712016],
       [0.00963257, 0.32323505, 0.28006036, 0.59109149, 0.6235419 ,
        0.12465137, 0.20253048, 0.40075165, 0.36072333, 0.25443082],
       [0.6882232 , 0.44165569, 0.01010562, 0.15853461, 0.34416147,
        0.26005251, 0.39246546, 0.46329653, 0.50586588, 0.50772762],
       [0.13041077, 0.30102696, 0.49755519, 0.95126424, 0.2902084 ,
        0.68921197, 0.46458173, 0.08571068, 0.12163365, 0.88063387],
       [0.42251008, 0.76629583, 0.45858822, 0.60215809, 0.19566175,
        0.35427279, 0.57568245, 0.1053732 , 0.39412219, 0.15830407],
       [0.44617169, 0.93042732, 0.19648553, 0.24196928, 0.83301726,
        0.60346046, 0.56655956, 0.50948391, 0.5351572 , 0.2824156 ],
       [0.29587533, 0.83396662, 0.22712706, 0.89453288, 0.95390442,
        0.41609135, 0.59320001, 0.09591303, 0.01858286, 0.40593103],
       [0.27459614, 0.87539998, 0.7511686

#### Create an array of 20 linearly spaced points between 0 and 1:

In [12]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [13]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [14]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [15]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [16]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [17]:
mat[3,4]

20

In [18]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [19]:
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [20]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [21]:
mat[4]

array([21, 22, 23, 24, 25])

In [22]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [23]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [24]:
np.sum(mat)

325

#### Get the standard deviation of the values in mat

In [25]:
np.std(mat)

7.211102550927978

#### Get the sum of all the columns in mat

In [26]:
np.sum(mat,axis=0)

array([55, 60, 65, 70, 75])

# Great Job!